-- ==========================================
-- TABLE DEFINITIONS
-- ==========================================

-- 1. Categories
CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  icon TEXT,
  description TEXT,
  gradient TEXT,
  image TEXT,
  count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  category_id TEXT REFERENCES categories(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  description TEXT,
  long_description TEXT,
  tags TEXT[],
  features TEXT[],
  size TEXT,
  length TEXT,
  colour_or_type TEXT,
  thickness TEXT,
  other_specs TEXT,
  specs JSONB,
  image TEXT,
  images TEXT[],
  use_cases TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Branches
CREATE TABLE IF NOT EXISTS branches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  hours TEXT NOT NULL,
  region TEXT NOT NULL,
  map_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Company Values
CREATE TABLE IF NOT EXISTS company_values (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  icon TEXT,
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Target Markets
CREATE TABLE IF NOT EXISTS target_markets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  icon TEXT,
  title TEXT NOT NULL,
  "desc" TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5a. Company Stats
CREATE TABLE IF NOT EXISTS company_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  value TEXT NOT NULL,
  label TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5b. Contact Info
CREATE TABLE IF NOT EXISTS contact_info (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  icon TEXT,
  label TEXT NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5c. Socials
CREATE TABLE IF NOT EXISTS socials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  href TEXT NOT NULL,
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5d. Team Members
CREATE TABLE IF NOT EXISTS team_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  department TEXT,
  bio TEXT,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Services
CREATE TABLE IF NOT EXISTS services (
  id TEXT PRIMARY KEY,
  icon TEXT,
  title TEXT NOT NULL,
  tagline TEXT,
  problem TEXT,
  approach TEXT,
  features TEXT[],
  outcomes TEXT,
  gradient TEXT,
  icon_bg TEXT,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Service Summaries
CREATE TABLE IF NOT EXISTS service_summaries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  icon TEXT,
  title TEXT NOT NULL,
  description TEXT,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Alerts
CREATE TABLE IF NOT EXISTS alerts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  content TEXT,
  severity TEXT,
  date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. News
CREATE TABLE IF NOT EXISTS news (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  content TEXT,
  category TEXT,
  date DATE,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Calendar Events
CREATE TABLE IF NOT EXISTS calendar_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  date DATE NOT NULL,
  type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. Resources
CREATE TABLE IF NOT EXISTS resources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  link TEXT,
  icon TEXT,
  target TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 12. Quote Requests (Client Portal / Formspree Hybrid)
CREATE TABLE IF NOT EXISTS quote_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  company TEXT,
  farm_size TEXT,
  location TEXT,
  pickup_location TEXT, -- Can be branch ID or raw text
  message TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 13. Quote Request Items
CREATE TABLE IF NOT EXISTS quote_request_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_request_id UUID REFERENCES quote_requests(id) ON DELETE CASCADE,
  product_id TEXT, -- No strict FK to allow quotes for deleted products
  product_name TEXT NOT NULL,
  category TEXT,
  quantity INTEGER NOT NULL DEFAULT 1,
  custom_notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 14. Blog Posts
CREATE TABLE IF NOT EXISTS blog_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  content TEXT,
  excerpt TEXT,
  image TEXT,
  author TEXT,
  published_at DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 15. Gallery Items
CREATE TABLE IF NOT EXISTS gallery_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT,
  type TEXT NOT NULL CHECK (type IN ('image', 'video')),
  url TEXT NOT NULL,
  width INTEGER,
  height INTEGER,
  caption TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE target_markets ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE socials ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE news ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_request_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery_items ENABLE ROW LEVEL SECURITY;

-- Create Policies for Public Read Access (Site Content)
CREATE POLICY "Public Read Access for Categories" ON categories FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Products" ON products FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Branches" ON branches FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Company Values" ON company_values FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Target Markets" ON target_markets FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Company Stats" ON company_stats FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Contact Info" ON contact_info FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Socials" ON socials FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Team Members" ON team_members FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Services" ON services FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Service Summaries" ON service_summaries FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Alerts" ON alerts FOR SELECT USING (true);
CREATE POLICY "Public Read Access for News" ON news FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Calendar Events" ON calendar_events FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Resources" ON resources FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Blog Posts" ON blog_posts FOR SELECT USING (true);
CREATE POLICY "Public Read Access for Gallery Items" ON gallery_items FOR SELECT USING (true);

-- Create Policies for Quote Submissions (Anyone can submit, but only admins can read)
CREATE POLICY "Public Insert Quote Requests" ON quote_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Insert Quote Request Items" ON quote_request_items FOR INSERT WITH CHECK (true);

-- Temporary policy to allow managing content without auth (Remove when auth is set up)
-- To enable admin management before Auth is built, uncomment these or add specific IP/User filters:
CREATE POLICY "Temp All Access Categories" ON categories FOR ALL USING (true);
CREATE POLICY "Temp All Access Products" ON products FOR ALL USING (true);
CREATE POLICY "Temp All Access Branches" ON branches FOR ALL USING (true);
CREATE POLICY "Temp All Access Company Values" ON company_values FOR ALL USING (true);
CREATE POLICY "Temp All Access Target Markets" ON target_markets FOR ALL USING (true);
CREATE POLICY "Temp All Access Company Stats" ON company_stats FOR ALL USING (true);
CREATE POLICY "Temp All Access Contact Info" ON contact_info FOR ALL USING (true);
CREATE POLICY "Temp All Access Socials" ON socials FOR ALL USING (true);
CREATE POLICY "Temp All Access Team Members" ON team_members FOR ALL USING (true);
CREATE POLICY "Temp All Access Services" ON services FOR ALL USING (true);
CREATE POLICY "Temp All Access Service Summaries" ON service_summaries FOR ALL USING (true);
CREATE POLICY "Temp All Access Alerts" ON alerts FOR ALL USING (true);
CREATE POLICY "Temp All Access News" ON news FOR ALL USING (true);
CREATE POLICY "Temp All Access Calendar Events" ON calendar_events FOR ALL USING (true);
CREATE POLICY "Temp All Access Resources" ON resources FOR ALL USING (true);
CREATE POLICY "Temp All Access Quote Requests" ON quote_requests FOR ALL USING (true);
CREATE POLICY "Temp All Access Quote Request Items" ON quote_request_items FOR ALL USING (true);
CREATE POLICY "Temp All Access Blog Posts" ON blog_posts FOR ALL USING (true);
CREATE POLICY "Temp All Access Gallery Items" ON gallery_items FOR ALL USING (true);

-- ==========================================
-- STORAGE BUCKETS
-- ==========================================

-- Ensure storage extension and schema exists (standard in Supabase)
-- Insert the public bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('afrodrip_assets', 'afrodrip_assets', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policy: Public Read
CREATE POLICY "Public Access for assets" ON storage.objects FOR SELECT 
USING (bucket_id = 'afrodrip_assets');

-- Storage Policy: Public Upload (Temporary, lock down later)
CREATE POLICY "Public Upload for assets" ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'afrodrip_assets');
CREATE POLICY "Public Update for assets" ON storage.objects FOR UPDATE 
WITH CHECK (bucket_id = 'afrodrip_assets');
CREATE POLICY "Public Delete for assets" ON storage.objects FOR DELETE 
USING (bucket_id = 'afrodrip_assets');
