export interface Branch {
  id: string;
  name: string;
  address: string;
  phone: string;
  email: string;
  hours: string;
  region: 'Metro Manila' | 'Luzon' | 'Visayas' | 'Mindanao';
}

export const branches: Branch[] = [
  {
    id: 'bgc',
    name: 'BGC (HQ)',
    address: '5th Avenue, Bonifacio Global City, Taguig, Metro Manila',
    phone: '+63 (2) 8123-4567',
    email: 'bgc@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Metro Manila',
  },
  {
    id: 'makati',
    name: 'Makati',
    address: 'Ayala Avenue, Makati City, Metro Manila',
    phone: '+63 (2) 8123-4568',
    email: 'makati@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Metro Manila',
  },
  {
    id: 'qc',
    name: 'Quezon City',
    address: 'North Avenue, Quezon City, Metro Manila',
    phone: '+63 (2) 8123-4569',
    email: 'qc@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Metro Manila',
  },
  {
    id: 'manila',
    name: 'Manila',
    address: 'Ermita, Manila, Metro Manila',
    phone: '+63 (2) 8123-4570',
    email: 'manila@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Metro Manila',
  },
  {
    id: 'cebu',
    name: 'Cebu City',
    address: 'Cebu IT Park, Lahug, Cebu City',
    phone: '+63 (32) 234-5678',
    email: 'cebu@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Visayas',
  },
  {
    id: 'davao',
    name: 'Davao City',
    address: 'Abreeza Hub, J.P. Laurel Avenue, Davao City',
    phone: '+63 (82) 345-6789',
    email: 'davao@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Mindanao',
  },
  {
    id: 'clark',
    name: 'Clark',
    address: 'Clark Freeport Zone, Pampanga',
    phone: '+63 (45) 456-7890',
    email: 'clark@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Luzon',
  },
  {
    id: 'baguio',
    name: 'Baguio City',
    address: 'Session Road, Baguio City',
    phone: '+63 (74) 567-8901',
    email: 'baguio@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Luzon',
  },
  {
    id: 'iloilo',
    name: 'Iloilo City',
    address: 'Iloilo Business Park, Mandurriao, Iloilo City',
    phone: '+63 (33) 678-9012',
    email: 'iloilo@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Visayas',
  },
  {
    id: 'cdo',
    name: 'Cagayan de Oro',
    address: 'Limketkai Center, Cagayan de Oro City',
    phone: '+63 (88) 789-0123',
    email: 'cdo@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Mindanao',
  },
  {
    id: 'bacolod',
    name: 'Bacolod City',
    address: 'Lacson Street, Bacolod City',
    phone: '+63 (34) 890-1234',
    email: 'bacolod@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Visayas',
  },
  {
    id: 'gensan',
    name: 'General Santos',
    address: 'Santiago Boulevard, General Santos City',
    phone: '+63 (83) 901-2345',
    email: 'gensan@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Mindanao',
  },
  {
    id: 'zamboanga',
    name: 'Zamboanga City',
    address: 'Mayor Jaldon Street, Zamboanga City',
    phone: '+63 (62) 012-3456',
    email: 'zamboanga@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Mindanao',
  },
  {
    id: 'naga',
    name: 'Naga City',
    address: 'Magsaysay Avenue, Naga City',
    phone: '+63 (54) 123-4567',
    email: 'naga@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Luzon',
  },
  {
    id: 'vigan',
    name: 'Vigan City',
    address: 'Calle Crisologo, Vigan City, Ilocos Sur',
    phone: '+63 (77) 234-5678',
    email: 'vigan@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Luzon',
  },
  {
    id: 'alabang',
    name: 'Alabang',
    address: 'Filinvest City, Alabang, Muntinlupa',
    phone: '+63 (2) 8123-4571',
    email: 'alabang@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Metro Manila',
  },
  {
    id: 'ortigas',
    name: 'Ortigas',
    address: 'ADB Avenue, Ortigas Center, Pasig City',
    phone: '+63 (2) 8123-4572',
    email: 'ortigas@dripph.com',
    hours: 'Mon-Fri 8:00 AM - 6:00 PM',
    region: 'Metro Manila',
  },
];
